pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = 'ap-southeast-1'
        AWS_DEFAULT_OUTPUT = 'text'
        ECRREPONAME = '667656621301.dkr.ecr.ap-southeast-1.amazonaws.com/pyapp'
        ECRCREDID = 'phule'
        GITREPO = 'https://github.com/PhuLeRock/infinitelambda.git'
        GITCREDID = 'phulegit'
    }

    stages {   
    
        stage('push test') {
            steps {
                shell ```
                echo ${ECRREPONAME}
                echo ${ECRCREDID}
                ```
                script {
                    docker.withRegistry('https://"${ECRREPONAME}", ecr:ap-southeast-1:"${ECRCREDID}"') {
                    docker.image(${ECRREPONAME}).push(1.0) 
                    }
                }
            }                    
        }
            
    }
}            