pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = 'ap-southeast-1'
        AWS_DEFAULT_OUTPUT = 'text'
        ECRREPONAME = '667656621301.dkr.ecr.ap-southeast-1.amazonaws.com/pyapp'
        ECRCREDID = 'phule'
        GITREPO = 'https://github.com/PhuLeRock/infinitelambda.git'
        GITCREDID = 'phulegit'
    }

    stages {   
    
        stage('push test') {
            steps {
                sh '''
                echo ${ECRREPONAME}
                echo ${ECRCREDID}
                echo end of echo
                '''
                script {
                    docker.withRegistry("https://667656621301.dkr.ecr.ap-southeast-1.amazonaws.com", ecr:ap-southeast-1:phule) {
                    docker.image(667656621301.dkr.ecr.ap-southeast-1.amazonaws.com/pyapp).push(1.0) 
                    }
                }
            }                    
        }
            
    }
}            