pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = "ap-southeast-1"
        AWS_DEFAULT_OUTPUT = "text"
    }
    stages {
        stage("git checkout") {
            steps {
                git credentialsId: 'phulegit', url: 'https://github.com/PhuLeRock/infinitelambda.git'
                sh 'ls -la'
            }
        }           
    
    stage('001') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'phule', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
            echo 'Hello world'
            sh '''
            /usr/bin/sed -i s,buildnumber,${BUILD_NUMBER},g s3static/index.html
            /usr/bin/sed -i s,gitrevision,${GIT_COMMIT},g s3static/index.html
            /usr/bin/aws s3 cp s3static/index.html s3://infinitedevopstest/ --acl public-read
            '''    
            }
        }
    }    
    }
}            